# Generated by Django 5.2.6 on 2025-09-18 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "char_class",
                    models.CharField(
                        choices=[
                            ("mage", "Mago"),
                            ("warrior", "Guerreiro"),
                            ("archer", "Arqueiro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("exp", models.IntegerField(default=0)),
                ("max_exp", models.IntegerField(default=100)),
                ("attribute_points", models.PositiveIntegerField(default=0)),
                ("max_hp", models.IntegerField(default=100)),
                ("hp", models.IntegerField(default=100)),
                ("max_mana", models.IntegerField(default=50)),
                ("mana", models.IntegerField(default=50)),
                ("max_stamina", models.IntegerField(default=100)),
                ("stamina", models.IntegerField(default=100)),
                ("training_start", models.DateTimeField(blank=True, null=True)),
                ("resting_start", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
