# Generated by Django 5.2.6 on 2025-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0002_charactersconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="arcane",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="constitution",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="courage",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="dexterity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="luck",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="strength",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
