# Generated by Django 5.2.6 on 2025-09-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_character_arcane_character_constitution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="char_class",
        ),
        migrations.AddField(
            model_name="character",
            name="emoji",
            field=models.CharField(default="😃", max_length=5),
        ),
    ]
