# Generated by Django 5.2.6 on 2025-09-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0004_remove_character_char_class_character_emoji"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="equipped_chest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="items.equipment",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_feet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="items.equipment",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_hands",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="items.equipment",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="items.equipment",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_necklace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="items.equipment",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_shoulders",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="items.equipment",
            ),
        ),
    ]
