# Generated by Django 5.2.6 on 2025-11-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_character_equipped_chest_character_equipped_feet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="gold",
            field=models.IntegerField(default=0),
        ),
    ]
