# Generated by Django 5.2.6 on 2025-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0006_character_gold"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="type",
            field=models.CharField(
                choices=[("player", "Player"), ("npc", "NPC"), ("monster", "Monster")],
                default="player",
                max_length=20,
            ),
        ),
    ]
