# Generated by Django 5.2.6 on 2025-11-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0008_alter_character_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[],
            options={
                "verbose_name": "Monstro",
                "verbose_name_plural": "Monstros",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("character.character",),
        ),
    ]
