# Generated by Django 5.2.6 on 2025-11-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0009_monster"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monster",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "verbose_name": "Monstro",
                "verbose_name_plural": "Monstros",
            },
        ),
    ]
