# Generated by Django 5.2.6 on 2025-11-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_alter_monster_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Monster",
        ),
    ]
