# Generated by Django 5.2.6 on 2025-09-18 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0001_initial"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_growth_rate", models.FloatField(default=1.5)),
                ("training_stamina_per_minute", models.IntegerField(default=5)),
                ("training_xp_per_minute", models.IntegerField(default=10)),
                ("rest_stamina_per_minute", models.IntegerField(default=5)),
                ("rest_hp_per_minute", models.IntegerField(default=5)),
                ("rest_mana_per_minute", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("emoji", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "gold_per_minute",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "xp_per_minute",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("required_level", models.IntegerField(default=1)),
                ("duration", models.IntegerField(default=5)),
                (
                    "drops",
                    models.ManyToManyField(
                        blank=True, related_name="jobs_that_drop", to="items.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterJobProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("multiplier", models.FloatField(default=1.0)),
                ("min_xp", models.IntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranks",
                        to="tasks.job",
                    ),
                ),
            ],
        ),
    ]
