# Generated by Django 5.2.6 on 2025-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasksConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_stamina_per_minute", models.IntegerField(default=5)),
                ("training_xp_per_minute", models.IntegerField(default=10)),
                ("rest_stamina_per_minute", models.IntegerField(default=5)),
                ("rest_hp_per_minute", models.IntegerField(default=5)),
                ("rest_mana_per_minute", models.IntegerField(default=5)),
            ],
        ),
        migrations.DeleteModel(
            name="GameConfig",
        ),
    ]
