# Generated by Django 5.2.6 on 2025-11-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0007_character_type"),
        ("items", "0007_remove_storeitem_sell_price"),
        ("tasks", "0002_tasksconfig_delete_gameconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(default="", max_length=1000)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("level_growth_rate", models.FloatField(default=1.5)),
            ],
        ),
        migrations.RemoveField(
            model_name="jobrank",
            name="job",
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="job",
            name="drops",
            field=models.ManyToManyField(blank=True, to="items.item"),
        ),
        migrations.AlterField(
            model_name="job",
            name="gold_per_minute",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="xp_per_minute",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("exp", models.IntegerField(default=0)),
                ("max_exp", models.IntegerField(default=100)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
                (
                    "profession_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.professiontype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="profession_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.professiontype",
            ),
        ),
        migrations.DeleteModel(
            name="CharacterJobProgress",
        ),
        migrations.DeleteModel(
            name="JobRank",
        ),
    ]
