# Generated by Django 5.2.6 on 2025-11-30 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0007_character_type"),
        ("tasks", "0003_professiontype_remove_jobrank_job_job_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration", models.IntegerField(default=5)),
                ("required_level", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterHunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        limit_choices_to={"type": "monster"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monster",
                        to="character.character",
                    ),
                ),
                (
                    "hunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.hunt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HuntMonster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chance", models.FloatField(default=100)),
                (
                    "hunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monsters",
                        to="tasks.hunt",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        limit_choices_to={"type": "monster"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
            ],
        ),
    ]
