# Generated by Django 5.2.6 on 2025-11-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_remove_storeitem_sell_price"),
        ("tasks", "0004_hunt_characterhunt_huntmonster"),
    ]

    operations = [
        migrations.AddField(
            model_name="huntmonster",
            name="gold_drop",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="huntmonster",
            name="item_drops",
            field=models.ManyToManyField(blank=True, to="items.item"),
        ),
        migrations.AddField(
            model_name="huntmonster",
            name="xp_drop",
            field=models.IntegerField(default=0),
        ),
    ]
