# Generated by Django 5.2.6 on 2025-12-01 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_huntmonster_gold_drop_huntmonster_item_drops_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterhunt",
            name="monster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_monster",
                to="tasks.huntmonster",
            ),
        ),
    ]
