# Generated by Django 5.2.6 on 2025-12-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_characterhunt_monster"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="description",
            field=models.TextField(
                default="Enfrente criaturas perigosas nesta caçada."
            ),
        ),
        migrations.AddField(
            model_name="hunt",
            name="difficulty",
            field=models.IntegerField(
                default=1, help_text="Dificuldade de 1 (mais fácil) a 5 (mais difícil)."
            ),
        ),
    ]
