# Generated by Django 5.2.6 on 2025-09-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EncounterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(blank=True)),
                ("winner", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
