# Generated by Django 5.2.6 on 2025-09-23 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="combat_skill",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="passive_skill",
        ),
        migrations.AddField(
            model_name="equipment",
            name="slot",
            field=models.CharField(
                choices=[
                    ("head", "Cabeça"),
                    ("necklace", "Colar"),
                    ("shoulders", "Ombros"),
                    ("chest", "Tronco"),
                    ("hands", "Mãos"),
                    ("feet", "Pés"),
                ],
                default="head",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PassiveSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger",
                    models.CharField(
                        help_text="ex: 'on_turn_start', 'on_receive_damage', 'every_3_turns'...",
                        max_length=100,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passive_skills",
                        to="items.equipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassiveEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        help_text="ex: 'attribute_mod', 'status_effect', 'deal_damage', etc.",
                        max_length=50,
                    ),
                ),
                ("target", models.CharField(default="self", max_length=10)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "passive_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="items.passiveskill",
                    ),
                ),
            ],
        ),
    ]
