# Generated by Django 5.2.6 on 2025-11-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_remove_equipment_combat_skill_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passiveskill",
            name="equipment",
        ),
        migrations.AddField(
            model_name="equipment",
            name="passive_skill",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Exemplo:\n        {\n            "name": "Espírito Guardião",\n            "trigger": "on_turn_start",\n            "description": "Flavor text",\n            "effects": [\n                {"type": "attribute_mod", "target": "self", "payload": {"attr": "strength", "value": 2}},\n                {"type": "status_effect", "target": "enemy", "payload": {"status": "burn", "duration": 2}}\n            ]\n        }\n        ',
            ),
        ),
        migrations.DeleteModel(
            name="PassiveEffect",
        ),
        migrations.DeleteModel(
            name="PassiveSkill",
        ),
    ]
