# Generated by Django 5.2.6 on 2025-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_remove_passiveskill_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Exemplo:\n        {\n            "attack": {\n                "type": "physical",\n                "style": "slash",\n                "value": 10\n            },\n            "defense": {\n                "type": "magic",\n                "value": 5\n            }\n        }\n        ',
            ),
        ),
    ]
