# Generated by Django 5.2.6 on 2025-11-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_character_equipped_chest_character_equipped_feet_and_more"),
        ("items", "0004_equipment_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="passive_skill",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Exemplo:\n        {\n            "name": "Espírito Guardião",\n            "trigger": "on_turn_start",\n            "description": "Flavor text",\n            "cost": 10,\n            "effects": [\n                {"type": "attribute_mod", "target": "self", "payload": {"attr": "strength", "value": 2}},\n                {"type": "status_effect", "target": "enemy", "payload": {"status": "burn", "duration": 2}}\n            ]\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Exemplo:\n        {\n            "attack": {\n                "type": "physical",\n                "style": "slash",\n                "value": 10\n            },\n            "defense": {\n                "type": "magic",\n                "weakness": "slash",\n                "value": 5\n            }\n        }\n        ',
            ),
        ),
        migrations.CreateModel(
            name="MarketListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.item"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="character.character",
                    ),
                ),
            ],
        ),
    ]
