# Generated by Django 5.2.6 on 2025-11-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_storeitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeitem",
            name="sell_price",
        ),
    ]
