# Generated by Django 5.2.6 on 2025-12-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_remove_storeitem_sell_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumable",
            name="crafting_recipe",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="material",
            name="crafting_recipe",
        ),
        migrations.AddField(
            model_name="item",
            name="recipe",
            field=models.JSONField(
                blank=True,
                help_text='\n        Exemplo:\n        {\n            [{"item_id":1, "qty":5}, {"item_id":2, "qty":5}]\n        }\n        ',
                null=True,
            ),
        ),
    ]
