# Generated by Django 5.2.6 on 2025-12-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_remove_consumable_crafting_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="recipe",
            field=models.JSONField(
                blank=True,
                help_text='\n        Exemplo:\n        {\n            "wood": "2", \n            "metal": "1"\n        }\n        ',
                null=True,
            ),
        ),
    ]
